In [1]:
# importing tensorflow under alias of tf
import tensorflow as tf

# Tensors

* A tensor is a vector generalized to higher dementions
* A tensor is represent as a n-dimensional array of base datatypes
* A vector is essentially a datapoint
* A vector can have any number of demensions

# Implementation of Tensors
* Each tensor has a datatype and shape
* It is rare to see a tensor with a non-number datatype
* Will almost always be float32 or int32

# Rank/Degree of Tensors
* Rank and Degree are synonyms
* Rank numbers can be thought of like dimensions; ie rank 0 is a point with 0 dimensions, rank 1 is a line with one dimension
* Rank in a tensor with this implementation can be found by looking at the deepest level of nested lists

In [3]:
# Example of creating rank 0 tensors
# Each one of these tensors only has one variable
# The datatype is defined by an argument passed to the "Variable" function last
rank_0_string = tf.Variable("this is a string", tf.string) # rare, but possible string datatype
rank_0_int = tf.Variable(324, tf.int16) # 16 bit int
rank_0_float = tf.Variable(3.567, tf.float64)

In [6]:
# Examples of Creating Rank 1 Tensors
# Each of these tensors have one array, and one dimension
rank_1_string = tf.Variable(["this", "is,", "a", "string"], tf.string)
rank_1_int = tf.Variable([1, 2, 3, 4 ,5], tf.int16)
rank_1_float = tf.Variable([1.1, 2.2, 3.3, 4.4, 5.5], tf.float64)

In [8]:
# Rank 2 Tensors, a nested list that is 1 deep
rank_2_string = tf.Variable([["this", "is"], ["a", "string"]], tf.string)
rank_2_int = tf.Variable([1, 2, 3], [4, 5], tf.int16)
rank_2_float = tf.Variable([[1.1, 2.2, 3.3, 4.4, 5.5]], tf.float64)

In [9]:
# The rank of tensor can be found with tf.rank()
print(tf.rank(rank_0_string))
print(tf.rank(rank_1_string))
print(tf.rank(rank_2_string))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


# Shape of a Tensor
* How many items in each dimension
* Different from rank

In [18]:
# shape of a tensor can be found using `<tensor_name>.shape`
# the aasnt of numbers it outputs is also the rank
print(rank_0_string.shape)
print(rank_1_string.shape) 
print(rank_2_string.shape)

()
(4,)
(2, 2)


# Disecting Above Output

The first output was `()` because it is a rank 0 tensor, so it does not have a shape. The second output was `(4,)` because there were found items in one array. The last output was `(2, 2)` because there are two items in two arrays.

# Changing Shape

* Many different shapes can represent the same number of elements
* Flattening will put all elements into a Rank 1 Tensor

# `tf.reshape`
* `tf.reshape` takes the following args in this order, `<tensor_to_be_changed>, <shape>`
* -1 will infer the shape based on already supplied data

In [21]:
tensor1 = tf.ones([1, 2, 3]) # tf.ones() creates a shape [1, 2, 3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape exisiting data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place
                                       # this will reshape the tensor to [3,2]

In [22]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Types of Tensors
* 